name: Hello world
on: 
  workflow_dispatch:
    inputs:
      Environment:
        description: Choose environment to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod
jobs:
  Hello-job:  #name of job
    runs-on: ubuntu-latest
    steps:
      - name: hello step
        run: |
          echo "Hello world"
          echo "${{inputs.Environment}}"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connecting to env
        env:
            APP_ENV: "test"
        run: echo "$APP_ENV"    
      - uses: actions/checkout@v4
      - run: cat index.html
          
