name: Hello world
on: workflow_dispatch
jobs:
  Hello-job:  #name of job
    runs-on: ubuntu-latest
    steps:
      - name: hello step
        run: echo "Hello world"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat index.html
          
